<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="5">

  <testsuite name="file.new_folder"
    errors="0" failures="1" hostname="" id="" package="file.new_folder" skipped="1"
    tests="5" time="0.000" timestamp="Wed, 30 Sep 2015 06:11:08 GMT">
  
    <testcase name="goorm_login" time="80.89" assertions="8">

    

    

    

    

    

    

    

    
    </testcase>
  
    <testcase name="project_open" time="5.679" assertions="3">

    

    

    
    </testcase>
  
    <testcase name="file_new_folder" time="5.205" assertions="5">

    

    

    

    

    
    </testcase>
  
    <testcase name="file_new_duplicate_folder" time="5.732" assertions="4">

    

    

      <failure message="Timed out while waiting for element &lt;#dlg_alert&gt; to be visible for 2000 milliseconds.">    at Object.module.exports.file_new_duplicate_folder (C:\Users\K1\projects\goorm-test\testcase\file\file.new_folder.js:48:8)
    at Module.call (C:\Users\K1\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:60:34)
    at C:\Users\K1\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:96:29
    at _fulfilled (C:\Users\K1\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\K1\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\K1\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\K1\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\K1\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\K1\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at process._tickCallback (node.js:355:11)</failure>

    
    </testcase>
  
  
    
    <testcase
      name="file_new_inappropriate_folder">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
